### ISSUE TITLE
New slogan for v2

### ISSUE THREAD

**Issue by aalemayhu** [imba/imba.io#101]
Now that Imba v2 is arriving soon, what should the new slogan on the front page be? Currently it's

> Create complex web apps with ease!

I think you can come up with something better, what do you think?

**Comment by somebee** [comment]
I really liked the one that @iamtirado used in a sketch. "The friendly full-stack language"

**Comment by scanf** [comment]
I think it sets the bar really high but why not. I will post this link on the gitter to solicit more feedback.

**Comment by altteo** [comment]
The language you will love

**Comment by Spaceghost** [comment]
Built for developers, tuned for {web,node,mobile}.

**Comment by XANOZOID** [comment]
Light on your head, light on the web; fast to type , faster than light... Booyah! Hahaha

Friendly, fast, and full of stack.

Your other framework can't do that. 

The fun part of web development. 

It makes business awesome: imba. 

Speed doesn't need to come with headaches.

A full full stack "speedy brain friend".

Imba: it's cozy in here! 

Imba: for everyone

Imba: the friendly, fast, and cozy full stack language

Imba: "productive fun" 

Imba: noun - stands for a 100% joyful time!

**Comment by familyfriendlymikey** [comment]
Epic rhymes Xanozoid 😂

Seems like we went with "The friendly full-stack language" so I'll close this for now.
