### ISSUE TITLE
Document each style modifier with examples

### ISSUE THREAD

**Issue by somebee** [imba/imba.io#134]
Currently a custom list - should rather copy (and improve upon) the way we document event modifiers

**Comment by familyfriendlymikey** [comment]
These appear to now be included on [docs/css/modifiers](https://imba.io/docs/css/modifiers) from [imba/typings/styles.modifiers.d.ts](https://github.com/imba/imba/blob/master/packages/imba/typings/styles.modifiers.d.ts), so I'll close this.
