### ISSUE TITLE
Move v2.imba.io to imba.io

### ISSUE THREAD

**Issue by aalemayhu** [imba/imba.io#146]
It's still a while until we can do this but all of the preparation on the deployment pipeline has been done. So when we are ready it's just a matter of merging v2 back into the master branch.

**Comment by Pistus** [comment]
I have setup a new server. Once everything is ready I will make v2 the new master, this will be served as the root on imba.io and current master will be served under v1.imba.io. Waiting for dns access so that I can setup wildcard ssl certs before switching.

**Comment by aalemayhu** [comment]
Ok, I sent out an invite to your Scrimba address, to the Imba on Gandi.net <http://gandi.net/>.

**Comment by eulores** [comment]
Ticket can be closed?

**Comment by Pistus** [comment]
yes it can
