### ISSUE TITLE
Documentation samples should actually compile without errors

### ISSUE THREAD

**Issue by eulores** [imba/imba.io#176]
#### Basic Syntax / Methods
```
def method name = 'imba'
	console.log param
```
should be
```
def method name = 'imba'
	console.log name
```
---
#### Basic Syntax / Class Declarations
```
let todo = new Todo 'Read introduction'
```
should be
```
let todo = new Todo title: 'Read introduction'
```
otherwise the constructor would not take `Read introduction` to initialize title.

---
#### Basic Syntax / Loops & Iteration
```
for num in array when num != 2
	num
```
`array` is undefined

---
#### Basic Syntax / Components
```
imba.mount <todo-app data=todos>
```
`todos` is undefined

**Comment by familyfriendlymikey** [comment]
These appear to have been fixed, thank you!
