### ISSUE TITLE
Array of maps undocumented?

### ISSUE THREAD

**Issue by eulores** [imba/imba.io#177]
At least I didn't find no reference in [arrays](https://imba.io/language/grammar/literals/arrays) or [objects](https://imba.io/language/grammar/literals/objects)

For example, this compiles fine 
```
let todos = [
	title:'one'
	completed:false
	-
	title:'two'
	completed:false
	-
	title:'three'
	completed:true
]
```
and is nicer to read than the alternative
```
let todos = [{title:'one', completed:false}, {title:'two', completed:false}, {title:'three', completed:true}]
```

**Comment by andregoldstein** [comment]
Not sure if this is because this style will be deprecated? If it's a keeper, I can add in an example to the docs
