### ISSUE TITLE
Call stack exceeded when using quick open

### ISSUE THREAD

**Issue by codeluggage** [imba/imba.io#227]
1. Press `cmd+k`
2. Type "tag"
3. Press `enter`
4. Nothing happens -> open console and see error:

![image](https://user-images.githubusercontent.com/1154150/157437295-7c05a7f6-e85a-440a-a403-de828ac6c72d.png)

**Comment by somebee** [comment]
Hmm, I couldn't get it to happen with your description, but I can reproduce the issue when clicking "Tags" in the sidebar on the literals page.
