### ISSUE TITLE
global search

### ISSUE THREAD

**Issue by scanf** [imba/imba.io#23]
Please consider adding search field to the pages. This makes it easier for beginners to quickly lookup syntax and related things. 

Thanks.

**Comment by JithinKS97** [comment]
Interested in taking up this issue. Any suggestions on tools that you guys prefer for implementing it.

**Comment by JithinKS97** [comment]
My idea is to put the search bar in the navbar where users type the search word and a drop down pops up with the search results. On clicking any of the result will lead the user to respecrive location where the content is present.

**Comment by scanf** [comment]
Sounds good, reassigned this to you. We might want to revisit it later when the site gets more content but a good start. 

I am not so good with frontend things yet so can't give you any input there but if you if you can add this feature without adding any new external dependencies that would be great! It might require some extra work but you could this by creating a search [component][2], take a look at the existing code in [src][1] for ideas.

[1]: https://github.com/imba/imba.io/tree/master/src/
[2]: http://imba.io/guides/essentials/custom-tags

**Comment by scanf** [comment]
@JithinKS97 how is it going?

**Comment by scanf** [comment]
We will be using GitBook moving forward so this is no longer relevant.
