### ISSUE TITLE
Add examples for ranges

### ISSUE THREAD

**Issue by scanf** [imba/imba.io#47]
```
# ranges
for item in [0...10] # exclusive
	item * 2
	
for item in [0..10] # inclusive (0 - 10)
	item * 2
```

Reference: https://scrimba.com/p/pJkZsB/cNRrLUL

**Comment by Sakshisrivastava413** [comment]
i will pick up this.

**Comment by scanf** [comment]
@Sakshisrivastava413 cool, you can add this to the [guide/2-Language/loops.md][0] file with an appropriate title. Take a look at the other examples and let me if you have any issues.

Thanks.

[0]: https://github.com/imba/imba.io/blob/master/guide/2-Language/loops.md
