### ISSUE TITLE
How to add event handler to standard element?

### ISSUE THREAD

**Issue by jkleiser** [imba/imba.io#6]
Is it possible to add an onclick handler to e.g. just one button element without first subclassing button? I didn't find this mentioned in the imba docs.
Handling onclick by subclassing of course worked:

```
tag clickable-button < button
   def onclick evt
      console.log("clickable-button onclick, target %s", evt.target)
```

**Comment by somebee** [comment]
Yes, you can add event-handlers with: `<button :click=()>` syntax. Here's a gist with some examples: https://gist.github.com/somebee/7d940b7c56acbf89f071. Sorry for the lack of documentation - a bunch of screencasts and better examples are on the way :)

**Comment by jkleiser** [comment]
Thanks!

**Comment by scanf** [comment]
The docs have improved since this issue was created. The docs page on [Event Handling][0] has examples.

Reference:  8ff46c804d25 (Working on guides, 2018-02-15)

[0]: http://imba.io/guides/essentials/event-handling#declaring-default-handlers
