### ISSUE TITLE
Add .github files from Imba project

### ISSUE THREAD

**Issue by scanf** [imba/imba.io#63]
The Imba project has several useful files for contributors. It would be nice to also have some of them here. This includes doing the following

- [ ] Copy the [imba/.github/PULL_REQUEST_TEMPLATE.md
](https://github.com/imba/imba/tree/master/.github/PULL_REQUEST_TEMPLATE.md) to `imba.io/.github/PULL_REQUEST_TEMPLATE.md`
- [ ] Copy [imba/.github/CODE_OF_CONDUCT.md](https://github.com/imba/imba/blob/master/.github/CODE_OF_CONDUCT.md) to `imba.io/.github/CODE_OF_CONDUCT.md`
- [ ] Copy [imba/.github/CONTRIBUTING.md](https://github.com/imba/imba/blob/master/.github/CONTRIBUTING.md) to `imba.io/.github/CONTRIBUTING.md`

**Comment by lucasmedeiros** [comment]
I can work on this :)
