### ISSUE TITLE
Could you explain that: <todo[todo]@{todo.id}>

### ISSUE THREAD

**Issue by bbodi** [imba/imba.io#7]
Could you explain the following row from TodoMVC-Imba code: 
app.imba: 92

```
<ul.todo-list>
    for todo in items
        <todo[todo]@{todo.id}>
           |    |   ^ ???
           |    ^ pass the todo object to the tag as their 'object' field
           ^ create a todo tag 
```

Sorry if you already mentioned it somewhere, but I couldn't find it in the docs.

**Comment by jveres** [comment]
Hi! That hints the compiler how to cache that DOM node for performance optimization. You can read a bit more here: https://github.com/somebee/imba/issues/9

**Comment by madmaniak** [comment]
@bbodi <code>@{todo.id}</code> this part is an equivalent of react <code>key=todo.id</code> which means you point data referencing well your element - needed for efficient reconciliation in collections.
